### ISSUE TITLE
New Skebby API - Roadmap

### ISSUE THREAD

**Issue by alekitto** [fazland/skebby-rest-client#18]
Skebby has revamped its API ([docs here](https://developers.skebby.it/?php#skebby-rest-api-introduction)).
This is a proposal for a roadmap to handle these new APIs.

Production base URL is `https://api.skebby.it/API/v1.0/REST/`

No indication for test API URL or testing/development/pre-production environment and/or send methods. If someone has these informations please add them as a response to this issue.

The current status of `master` branch will be released as `0.3.1` and a new `1.x` branch will be opened from that point.
Base client needs refactor to handle the new authentication methods.

After that I split the work into 3 priority blocks (tiers). Each one could represent a `semver-minor` release.

Needs refactor (SEMVER-MAJOR):

- Client and authentication
  - build on top of [`solido/atlante-php`](https://github.com/solid-o/atlante-php)
  - handle session key (or auth token?) via atlante Storage classes

Tier 1:

- [ ] `Sms` resource
  - [ ] encoding detection
  - [ ] `send`/`sendWithParameters` API (https://developers.skebby.it/?php#sms-send-api)
  - [ ] `webhook` processing (https://developers.skebby.it/?php#enable-webhook-on-sms-delivery-received)

- [ ] `2FA` resource (https://developers.skebby.it/?php#two-factor-authentication-api)
- [ ] `status` resource with remaining SMS credits (https://developers.skebby.it/?php#sms-credits-and-email-service-status)

Tier 2:

- [ ] `TPOA` (https://developers.skebby.it/?php#tpoa-api)
- [ ] `Blacklist` (https://developers.skebby.it/?php#sms-blacklist-stop-sms)
- [ ] `Received messages` (https://developers.skebby.it/?php#received-sms-api)
- [ ] `Contacts` (https://developers.skebby.it/?php#contacts-api)
- [ ] `Contact groups` (https://developers.skebby.it/?php#contacts-groups-api)

Tier 3:

- [ ] `History` (https://developers.skebby.it/?php#sms-history-api)
- [ ] `Subaccount` (https://developers.skebby.it/?php#subaccount-api)
- [ ] `Landing pages` (https://developers.skebby.it/?php#landing-pages-api)

Any thoughts about this?
